README.md, cmd/select_query.go, go.mod
- add readme and example useage
=> chore: add readme and example useage

cmd/select_query.go, connection.go, dsn.go, restful.go
=> feat: support accesstoken to db

interpolate.go, rows.go
=> fix query sync next

.github/workflows/ci.yaml, dsn.go, dsn_test.go
ref: https://github.com/xo/dburl/pull/24
=> feat: support scheme with argument sslmode

dsn.go, dsn_test.go
ref: https://github.com/xo/dburl/pull/24
=> fix: support dsn bend://

query.go, restful.go
for: https://github.com/databendcloud/bendsql/issues/44
=> fix: wait for result if query running

access_token.go, dsn.go, restful.go, restful_test.go
=> Add access token loader to Config

access_token.go, connection.go, dataparser.go, dsn.go, dsn_test.go, encoder.go, helpers.go, query.go, restful.go, types.go
=> fix: set database in session config for query request

rows.go
for: https://github.com/databendcloud/bendsql/issues/67
=> fix: no schema in final page

con_batch.go, connection.go, lib/driver/driver.go, query.go, restful.go, stmt.go
* replace copy into with stage insert
=> feat: export UploadToStage for APIClient

access_token.go
- currently the token file is restricted as a toml format, which limitted it can not take the kubernete's bound service account token.
=> fix: allow parse kubernete's jwt token file 

README.md, tests/main_test.go
fix https://github.com/datafuselabs/databend-go/issues/72
=> fix: code examples

con_batch.go, connection.go, restful.go, restful_test.go, rows.go
=> feat: process context in queries

dataparser.go, tests/main_test.go
Fix https://github.com/datafuselabs/databend-go/issues/63
=> fix: null type parse

connection.go
- pass queryid in client to make sure the queryid header in every request
- keep queryid header for load balance to fix https://github.com/datafuselabs/databend/issues/14080
=> fix: pass queryid in client

dataparser.go, tests/main_test.go
Fix https://github.com/datafuselabs/databend-go/issues/95
=> fix: quote string in query return valued truncated

restful.go, restful_test.go
1. group the session infos together,  update as a whole. make it easier when add more field to SessionState.
2. update SessionState on each resp.
=> refactor session.

connection.go, query.go, query_test.go, restful.go, stmt.go, tests/docker-compose.yml, tests/main_test.go, tests/session_test.go, transaction.go
- part of https://github.com/datafuselabs/databend/issues/14789
=> feat: support transaction

restful.go
due to https://github.com/datafuselabs/databend/pull/14908
=> fix schema: the first resp may not contain schema.

tests/main_test.go
=> ci: enhance test case for multi-pages result.

dsn.go, dsn_test.go
Fix session params config failed.
=> fix: session params config

const.go, query.go, restful.go
already checked with  https://github.com/datafuselabs/databend/pull/15621
=> feat: check node id for next_uri.

tests/session_test.go
wait for https://github.com/datafuselabs/databend/pull/16239
=> ci: add test for variable.

client.go, errors.go, tests/txn_test.go
currently it seems that the error did not contain the query error's code message, etc
=> fix: Unmarshal resp if possible

.github/workflows/ttc.yaml, access_token.go, client.go, connection.go, driver.go, dsn.go, query_test.go, rows.go, rows_hack.go, tests/ttc/Dockerfile, tests/ttc/main.go
Only ttc server and workflow are included in this pr, not bug fixes.
part of #145
=> feat: ttc intergration 
